services:
  app:
    image: digimarket-backend:latest
    container_name: digimarket_app
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - APP_ENV=production
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - storage_data:/var/www/html/storage/app
      - logs_data:/var/www/html/storage/logs
    networks:
      - digimarket-net

  postgres:
    image: postgres:17-alpine
    container_name: digimarket_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: digimarket_backend_v2
      POSTGRES_USER: sail
      POSTGRES_PASSWORD: idkpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sail -d digimarket_backend_v2"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - digimarket-net

volumes:
  postgres_data:
  storage_data:
  logs_data:

networks:
  digimarket-net:
    external: true